#include <stdio.h>
#include <stdlib.h>
#include <CUnit/Basic.h>

void testInsertAtNegativePosition();
void testInsertAtNULL();
void testInsertAtFirstPosition();
void testInsertAtMiddlePosition();
void testCreateElement();
void testDeleteFromNegativePosition();
void testDeleteFromNULL();
void testDeleteFromFirstPosition();
void testDeleteFromMiddlePosition();
void testDeleteFromEndPosition();
void testDeleteSingleElement();
void testListSize();
void testSingleElementSize();
void testNULLSize();
void testArrayToList();
void testNULLToList();
void testListToArray();
void testComparison();
void testIsWordEnd();
void testCountWords();
void testCountLetters();
void testCutFirstWord();
void testLtrim();
void testWordProcessing();
void testTextProcessing();
void testAdvancedTextProcessing();
void testLoremIpsumProcessing();
void testCountWordsArray();
void testWordlen();
void testCmpWithFirstWord();
void testFindNextWord();
void testFindFirstWord();
